In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
phase5_results = pd.read_csv("phase5_validation_results.csv")

phase5_results

,Model,Lookback,MAE,MSE,RMSE,MAPE,R2,Bias
0,RNN,24 hours,2934.691966,1.507680e+07,3882.885505,8.381019,0.509915,-2164.579669
1,RNN,48 hours,2804.554276,1.337679e+07,3657.429797,8.108753,0.565176,-1811.251916
2,RNN,168 hours,3091.808792,1.631260e+07,4038.886552,9.044437,0.469744,-1584.123233
3,LSTM,24 hours,2927.467063,1.455961e+07,3815.705578,8.338201,0.526727,-2346.953335
4,LSTM,48 hours,2975.498900,1.507415e+07,3882.544249,8.572470,0.510001,-2405.554376
5,LSTM,168 hours,2753.207870,1.250400e+07,3536.100119,8.019766,0.593546,-1905.002036
6,GRU,24 hours,2995.379049,1.501655e+07,3875.118779,8.514461,0.511874,-2440.578961
7,GRU,48 hours,2941.408518,1.399695e+07,3741.250010,8.494127,0.545017,-2401.765038
8,GRU,168 hours,2907.838106,1.410485e+07,3755.642477,8.411296,0.541509,-2263.152849
9,Bi-LSTM,24 hours,2991.414989,1.523597e+07,3903.328432,8.521060,0.504741,-2418.475490
10,Bi-LSTM,48 hours,2826.661405,1.388515e+07,3726.277780,8.073060,0.548651,-2308.041491
11,Bi-LSTM,168 hours,2828.005018,1.353820e+07,3679.429539,8.128915,0.559929,-2301.413998

In [3]:
phase5_results.sort_values(
    by="R2",
    ascending=False
)
best_phase5 = phase5_results.loc[
    phase5_results["R2"].idxmax()
]

best_phase5

Model                  LSTM
Lookback          168 hours
MAE              2753.20787
MSE         12504004.051972
RMSE            3536.100119
MAPE               8.019766
R2                 0.593546
Bias           -1905.002036
Name: 5, dtype: object

In [4]:
phase6_results = pd.read_csv("phase6_rnn_final_comparison.csv")

phase6_results

,Experiment,MAE,RMSE,MAPE,R2,Bias
0,Phase 5 RNN-48 Baseline,2213.295950,3018.200386,6.799618,0.783598,-1181.449405
1,RNN-48 + Time Features,2338.989995,2961.051034,7.132572,0.714994,-328.877632
2,RNN-48 + Time + Lag Features,2894.430283,3684.343609,8.944598,0.571222,892.884104
3,RNN-48 + Time + Lag + Rolling Features,2045.282073,2569.550332,6.362701,0.799563,614.004363
4,RNN-48 + Time + Lag + Rolling Features,2045.282073,2569.550332,6.362701,0.799563,614.004363
5,RNN-48 + Dropout,2236.203850,2774.639727,7.014936,0.766291,593.137957
6,RNN-48 + Batch Normalization,4421.516925,5620.627127,12.949586,0.040970,-1591.822013
7,RNN-48 + RMSprop,2897.984130,3482.218456,9.107735,0.631893,610.634055
8,RNN-48 + RMSprop + LR Scheduling,18707.087116,22432.246512,56.229193,-14.275946,-17283.056916
9,RNN-48 + RMSprop + LR Scheduling,2102.411521,2670.445912,6.501120,0.783514,123.542595
10,RNN-48 + RMSprop + LR Scheduling + Early Stopping,2385.324975,2990.615787,7.351098,0.728491,154.019297
11,RNN-48 + RMSprop + LR Scheduling + Early Stopp...,2326.750397,2921.702505,7.241754,0.740860,308.128101
12,RNN-48 + 2 Layers (64-32),3003.001419,3636.364202,9.269019,0.598582,208.944454
13,RNN-48 Hyperparameter Tuning,2288.766682,2838.880729,7.094536,0.755343,265.951903

In [5]:
phase6_results.sort_values(
    by="R2",
    ascending=False
)
phase6_best1 = phase6_results.loc[
    phase6_results["R2"].idxmax()
]

phase6_best1

Experiment    RNN-48 + Time + Lag + Rolling Features
MAE                                      2045.282073
RMSE                                     2569.550332
MAPE                                        6.362701
R2                                          0.799563
Bias                                      614.004363
Name: 3, dtype: object

In [6]:
phase6_results = pd.read_csv("phase6_LSTM_final_comparison.csv")

phase6_results

,Experiment,MAE,RMSE,MAPE,R2,Bias
0,Phase 5 LSTM-168 Baseline,2115.964600,2838.328335,6.517342,0.808623,-1236.143754
1,LSTM-168 + Time Features,1633.993795,2239.181409,4.847081,0.837018,-271.285156
2,LSTM-168 + Time + Lag Features,1699.106699,2265.111683,5.095458,0.837934,-263.490014
3,LSTM-168 + Time + Lag + Rolling Features,1620.934066,2178.920978,4.872283,0.855873,-388.072200
4,LSTM-168 + Dropout,1832.706852,2386.402107,5.470296,0.827118,-692.875503
5,LSTM-168 + Batch Normalization,4388.166616,5575.760019,12.990173,0.056220,-1312.587160
6,LSTM-168 + RMSprop,2546.784354,3140.024496,7.872365,0.700685,248.239997
7,LSTM-168 + RMSprop + LR Scheduling,2598.370160,3183.584943,8.010613,0.692323,187.037678
8,LSTM-168 + RMSprop + LR Scheduling + Early Sto...,2634.539679,3218.181390,8.138823,0.685599,224.721218
9,LSTM-168 + RMSprop + LR Scheduling + Early Sto...,3135.007312,3762.037605,9.727420,0.570356,357.934415
10,LSTM-168 + 2 Layers (64-32),2774.917854,3386.866621,8.606876,0.651776,344.091747
11,LSTM-168 Hyperparameter Tuning,2401.744759,2971.692354,7.424258,0.731916,229.875895

In [7]:
phase6_results.sort_values(
    by="R2",
    ascending=False
)
phase6_best2 = phase6_results.loc[
    phase6_results["R2"].idxmax()
]

phase6_best2

Experiment    LSTM-168 + Time + Lag + Rolling Features
MAE                                        1620.934066
RMSE                                       2178.920978
MAPE                                          4.872283
R2                                            0.855873
Bias                                         -388.0722
Name: 3, dtype: object

In [8]:
phase6_results = pd.read_csv("phase6_gru_final_comparison.csv")

phase6_results

,Experiment,MAE,RMSE,MAPE,R2,Bias
0,Phase 5 GRU-168 Baseline,2152.241307,2920.163692,6.594572,0.797428,-1355.285005
1,GRU-168 + Time Features,1675.188759,2268.595255,4.995853,0.832708,-221.315549
2,GRU-168 + Time + Lag Features,1688.835670,2312.508395,4.967767,0.831081,-867.102203
3,GRU-168 + Time + Lag + Rolling Features,1590.667643,2171.728658,4.752545,0.856823,-449.427243
4,GRU-168 + Dropout,1780.415825,2325.430228,5.460511,0.835839,-175.395698
5,GRU-168 + Batch Normalization,5030.354422,6597.034767,14.646533,-0.321174,-2173.165662
6,GRU-168 + RMSprop,2643.639751,3245.249919,8.116591,0.680288,33.683749
7,GRU-168 + RMSprop + LR Scheduling,2706.275406,3297.526526,8.330159,0.669905,146.346431
8,GRU-168 + RMSprop + LR Scheduling + Early Stop...,2707.845181,3277.071076,8.414681,0.673987,363.276122
9,GRU-168 + RMSprop + LR Scheduling + Early Stop...,3117.956332,3740.631712,9.715181,0.575231,533.572256
10,GRU-168 + RMSprop + LR Scheduling + Early Stop...,3117.956332,3740.631712,9.715181,0.575231,533.572256
11,GRU-168 + 2 Layers (64-32),2906.787300,3538.290865,9.045198,0.619942,267.738074
12,GRU-168 + 2 Layers (64-32),2906.787300,3538.290865,9.045198,0.619942,267.738074
13,GRU-168 Hyperparameter Tuning,2324.746501,2893.317702,7.126574,0.745871,13.252372

In [9]:
phase6_results.sort_values(
    by="R2",
    ascending=False
)
phase6_best3 = phase6_results.loc[
    phase6_results["R2"].idxmax()
]

phase6_best3

Experiment    GRU-168 + Time + Lag + Rolling Features
MAE                                       1590.667643
RMSE                                      2171.728658
MAPE                                         4.752545
R2                                           0.856823
Bias                                      -449.427243
Name: 3, dtype: object

In [10]:
phase6_results = pd.read_csv("phase6_bilstm_final_comparison.csv")

phase6_results

,Experiment,MAE,RMSE,MAPE,R2,Bias
0,Phase 5 bilstm-48 Baseline,2120.811443,2889.450767,6.455979,0.801667,-1297.351713
1,bilstm-48 + Time Features,1707.111232,2325.090452,5.033614,0.824272,-453.275668
2,bilstm-48 + Time + Lag Features,1699.733155,2239.109140,5.103314,0.841634,-170.774868
3,bilstm-48 + Time + Lag + Rolling Features,1678.903587,2189.625023,5.145930,0.854453,206.551840
4,bilstm-48 + Dropout,1749.704313,2288.787654,5.306878,0.840972,-251.300005
5,bilstm-48 + Batch Normalization,4996.753740,6366.270092,14.756804,-0.230361,-1562.486567
6,bilstm-48 + RMSprop,2822.337342,3437.507823,8.693338,0.641285,196.379411
7,bilstm-48 + RMSprop + LR Scheduling,2814.531897,3426.320066,8.725403,0.643616,363.498241
8,bilstm-48 + RMSprop + LR Scheduling + Early St...,2799.251553,3422.464210,8.617806,0.644417,128.045998
9,bilstm-48 + RMSprop + LR Scheduling + Early St...,3685.190514,4319.396280,11.478469,0.433619,719.797693
10,bilstm-48 + 2 Layers (64-32),3019.188058,3611.859266,9.449334,0.603974,569.573621
11,bilstm-48 Hyperparameter Tuning,2530.466742,3114.248771,7.833001,0.705579,322.257024

In [11]:
phase6_results.sort_values(
    by="R2",
    ascending=False
)
phase6_best4 = phase6_results.loc[
    phase6_results["R2"].idxmax()
]

phase6_best4

Experiment    bilstm-48 + Time + Lag + Rolling Features
MAE                                         1678.903587
RMSE                                        2189.625023
MAPE                                            5.14593
R2                                             0.854453
Bias                                          206.55184
Name: 3, dtype: object

In [12]:
phase6_results = pd.read_csv("phase7_validation_comparison.csv")

phase6_results

  Metric        30-Day        60-Day
0    MAE  1.407508e+03  1.703376e+03
1    MSE  3.283891e+06  5.376326e+06
2   RMSE  1.812151e+03  2.318691e+03
3   MAPE  4.758344e+00  4.995226e+00
4     R2  7.396601e-01  8.210248e-01
5   Bias  2.076982e+02 -4.037432e+02